
    let coffeetypes=[
        {name:"Arabica",img:"https://images.prismic.io/super-coffee/9f3a99ea-df4d-46a7-83fd-835815059149_arabica-coffee.jpg?auto=compress,format&rect=0,0,1500,1200&w=1200&h=960",des:`You may have seen bags of coffee labeled "100 percent Arabica." Arabica is the most popular type of bean used for coffee. Arabica beans are considered higher quality than Robusta, and they're also more expensive. They result in coffee with a sweeter, less harsh taste.`},
        {name:"Robusta",img:"https://static.toiimg.com/thumb/msid-90862215/90862215.jpg?width=500&resizemode=4",des:`Robusta beans are typically cheaper to produce because the Robusta plant is easier to grow. They have a higher caffeine content and taste more bitter than Arabica beans. These beans are often used to make instant coffee and espresso blends.`},
        {name:"Black Coffee",img:"https://sp-ao.shortpixel.ai/client/q_lqip,ret_wait,w_1920,h_1024/https://cdn-blog.credihealth.com/wp-content/uploads/2022/08/raimond-klavins-uAk731NvaJo-unsplash-1920x1024.jpg",des:`No frills here: Black coffee is made from plain ground coffee beans that are brewed hot. It's served without added sugar, milk, or flavorings.`}
    ,{name:"Decaf",img:"https://static.toiimg.com/photo/76797597.cms",des:"Coffee beans naturally contain caffeine, but roasters can use several different processes to remove almost all of it. Decaf coffee is brewed with these decaffeinated beans."},
    {name:"Cappuccino",img:"https://denverbeverage.com/wp-content/uploads/2019/03/Mocha_Cappuccino_2048x.jpg",des:`This espresso-based drink is similar to a latte, but the frothy top layer is thicker. The standard ratio is equal parts espresso, steamed milk, and foam. It's often served in a 6-ounce cup (smaller than a latte cup) and can be topped with a sprinkling of cinnamon.`},
    {name:"Macchiato",img:"https://coffeeatthree.com/wp-content/uploads/caramel-macchiato-featured.jpg",des:`A macchiato is a shot of espresso with just a touch of steamed milk or foam. In Italian, macchiato means "stained" or "spotted," so a caffè macchiato refers to coffee that's been stained with milk.`}
   , {name:"Americano",img:"https://img.freepik.com/premium-photo/classic-americano-coffee-with-milk-gray-background_112304-1304.jpg",des:`Order this drink and you'll get a shot of espresso diluted with hot water.`},
{name:"Cortado",img:"https://coffeeaffection.com/wp-content/uploads/2021/02/Cortado.jpg",des:`This drink, which hails from Spain, is half espresso, half steamed milk. Unlike many Italian coffee drinks, it contains little to no foam. It's typically served in a 4.5-ounce glass.`}
,{name:"Flat White",img:"https://cdn.vox-cdn.com/thumbor/ZrksPGXGEge0_XVLWgAOQ1C3U5g=/0x0:1000x750/1400x1400/filters:focal(0x0:1000x750):format(jpeg)/cdn.vox-cdn.com/uploads/chorus_image/image/45140100/6792268281_d0822743b8_b.0.0.jpg",des:`Like the latte, this drink consists of espresso and steamed milk, but the ratio of espresso to milk is higher. Baristas also fold the milk as it steams, which creates a more velvety texture. The flat white has roots in Australia and New Zealand.`}
]

   export let types=coffeetypes